//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Type
    {
        public Account_Type()
        {
            this.t_account_my_client = new HashSet<t_account_my_client>();
        }
    
        public string value { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<t_account_my_client> t_account_my_client { get; set; }
    }
}
