//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Info
    {
        public Branch_Info()
        {
            this.t_account_my_client = new HashSet<t_account_my_client>();
            this.t_entity = new HashSet<t_entity>();
            this.t_person_my_client = new HashSet<t_person_my_client>();
            this.userInfoes = new HashSet<userInfo>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
    
        public virtual ICollection<t_account_my_client> t_account_my_client { get; set; }
        public virtual ICollection<t_entity> t_entity { get; set; }
        public virtual ICollection<t_person_my_client> t_person_my_client { get; set; }
        public virtual ICollection<userInfo> userInfoes { get; set; }
    }
}
