//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cibLatestEntities : DbContext
    {
        public cibLatestEntities()
            : base("name=cibLatestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CODE_CONTRACT_TYPE> CODE_CONTRACT_TYPE { get; set; }
        public virtual DbSet<CODE_COUNTRY> CODE_COUNTRY { get; set; }
        public virtual DbSet<CODE_LEGALFORM> CODE_LEGALFORM { get; set; }
        public virtual DbSet<CODE_OWNER_DOCUMENT_TYPE> CODE_OWNER_DOCUMENT_TYPE { get; set; }
        public virtual DbSet<CODE_SECTORTYPE> CODE_SECTORTYPE { get; set; }
        public virtual DbSet<CODE_SHAREHOLDER_TYPE> CODE_SHAREHOLDER_TYPE { get; set; }
        public virtual DbSet<CONTRACT_DETAILS> CONTRACT_DETAILS { get; set; }
        public virtual DbSet<CONTRACT_GENERAL_INFO> CONTRACT_GENERAL_INFO { get; set; }
        public virtual DbSet<LINK_SUBJECT_CONTRACT> LINK_SUBJECT_CONTRACT { get; set; }
        public virtual DbSet<LINK_SUBJECT_SUBJECT> LINK_SUBJECT_SUBJECT { get; set; }
        public virtual DbSet<SUBJECT_INFORMATION> SUBJECT_INFORMATION { get; set; }
        public virtual DbSet<CODE_CONTRACT_PHASE> CODE_CONTRACT_PHASE { get; set; }
        public virtual DbSet<CODE_CONTRACT_STATUS> CODE_CONTRACT_STATUS { get; set; }
        public virtual DbSet<CODE_CURRENCY> CODE_CURRENCY { get; set; }
        public virtual DbSet<CODE_ECO_PURPOSE_CODE> CODE_ECO_PURPOSE_CODE { get; set; }
        public virtual DbSet<CODE_ENTERPRISE_TYPE> CODE_ENTERPRISE_TYPE { get; set; }
        public virtual DbSet<CODE_INSTALMENT_TYPE> CODE_INSTALMENT_TYPE { get; set; }
        public virtual DbSet<CODE_LEASED_GOODS_TYPE> CODE_LEASED_GOODS_TYPE { get; set; }
        public virtual DbSet<CODE_NEW_OR_USED_GOODS_FLAG> CODE_NEW_OR_USED_GOODS_FLAG { get; set; }
        public virtual DbSet<CODE_PAYMENT_METHOD> CODE_PAYMENT_METHOD { get; set; }
        public virtual DbSet<CODE_PAYMENT_PERIODICITY> CODE_PAYMENT_PERIODICITY { get; set; }
        public virtual DbSet<CODE_PERSONAL_GUARANTEE_TYPE> CODE_PERSONAL_GUARANTEE_TYPE { get; set; }
        public virtual DbSet<CODE_PREFINANCE_LOAN_FLAG> CODE_PREFINANCE_LOAN_FLAG { get; set; }
        public virtual DbSet<CODE_REAL_GUARANTEE_TYPE> CODE_REAL_GUARANTEE_TYPE { get; set; }
        public virtual DbSet<CODE_REORGANIZED_CREDIT_FLAG> CODE_REORGANIZED_CREDIT_FLAG { get; set; }
        public virtual DbSet<CODE_SUBSIDIZED_CREDIT_FLAG> CODE_SUBSIDIZED_CREDIT_FLAG { get; set; }
        public virtual DbSet<ERROR_REPORTED> ERROR_REPORTED { get; set; }
        public virtual DbSet<FILLER> FILLERs { get; set; }
        public virtual DbSet<OWNER_INFO> OWNER_INFO { get; set; }
    }
}
