//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_DETAILS
    {
        public string accountingPeriod { get; set; }
        public string contractNature { get; set; }
        public string fiContCode { get; set; }
        public string fiSubCode { get; set; }
        public string sanctionLimit { get; set; }
        public string totOutstandingAmount { get; set; }
        public string totalDisAmount { get; set; }
        public string instalmentNo { get; set; }
        public string paymentPeriodicity { get; set; }
        public string paymentMethod { get; set; }
        public string InstalmentAmount { get; set; }
        public string nextInstalmentExpDate { get; set; }
        public string nextInstalmentExpAmount { get; set; }
        public string remainingInstalmentNo { get; set; }
        public string remainingAmount { get; set; }
        public string overdueNotPaidNo { get; set; }
        public string overdueNotPaidAmount { get; set; }
        public string noOfDaysPaymentDelay { get; set; }
        public string leasedGoodType { get; set; }
        public string leasedGoodValue { get; set; }
        public string regNo { get; set; }
        public string manufactureDate { get; set; }
        public string dueForRecovery { get; set; }
        public string recoveryDuringPeriod { get; set; }
        public string cumRecovery { get; set; }
        public string lawsuiteDate { get; set; }
        public string classificationDate { get; set; }
        public string rescheduledTimesNo { get; set; }
        public string lastRescheduleDate { get; set; }
        public string ecoPurposeCode { get; set; }
        public string sme { get; set; }
        public string enterpriseType { get; set; }
        public string createDate { get; set; }
        public string upadateDate { get; set; }
    }
}
