//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_GENERAL_INFO
    {
        public string accountingPeriod { get; set; }
        public string recType { get; set; }
        public string contractNature { get; set; }
        public string fiCode { get; set; }
        public string branch { get; set; }
        public string fiSubCode { get; set; }
        public string fiContCode { get; set; }
        public string contType { get; set; }
        public string contPhase { get; set; }
        public string contStatus { get; set; }
        public string curr { get; set; }
        public string contStartDate { get; set; }
        public string contRequestDate { get; set; }
        public string contPlannedEndDate { get; set; }
        public string contActualEndDate { get; set; }
        public string defaultStatus { get; set; }
        public string lastPaymentDate { get; set; }
        public string isSubsidized { get; set; }
        public string isPreFinanced { get; set; }
        public string isReOrganized { get; set; }
        public string thirdPartyGuaranteeType { get; set; }
        public string SecurityType { get; set; }
        public string thirdPartyGuaranteeAmount { get; set; }
        public string SecurityAmount { get; set; }
        public string classificationbasis { get; set; }
        public string filler { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string isGuaranted { get; set; }
        public string hasCoBorrower { get; set; }
        public string isRejected { get; set; }
    }
}
