//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Type
    {
        public Contact_Type()
        {
            this.t_address = new HashSet<t_address>();
            this.t_person_employer = new HashSet<t_person_employer>();
            this.t_person_employer1 = new HashSet<t_person_employer>();
            this.t_phone = new HashSet<t_phone>();
        }
    
        public int tph_contact_type_id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<t_address> t_address { get; set; }
        public virtual ICollection<t_person_employer> t_person_employer { get; set; }
        public virtual ICollection<t_person_employer> t_person_employer1 { get; set; }
        public virtual ICollection<t_phone> t_phone { get; set; }
    }
}
