//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Codes
    {
        public Country_Codes()
        {
            this.director_detail = new HashSet<director_detail>();
            this.director_detail1 = new HashSet<director_detail>();
            this.director_detail2 = new HashSet<director_detail>();
            this.director_detail3 = new HashSet<director_detail>();
            this.director_detail4 = new HashSet<director_detail>();
            this.signatoryDetails = new HashSet<signatoryDetail>();
            this.signatoryDetails1 = new HashSet<signatoryDetail>();
            this.signatoryDetails2 = new HashSet<signatoryDetail>();
            this.signatoryDetails3 = new HashSet<signatoryDetail>();
            this.signatoryDetails4 = new HashSet<signatoryDetail>();
            this.t_address = new HashSet<t_address>();
            this.t_entity = new HashSet<t_entity>();
            this.t_from = new HashSet<t_from>();
            this.t_from_my_client = new HashSet<t_from_my_client>();
            this.t_person_employer = new HashSet<t_person_employer>();
            this.t_person_identification = new HashSet<t_person_identification>();
            this.t_person_my_client = new HashSet<t_person_my_client>();
            this.t_person_my_client1 = new HashSet<t_person_my_client>();
            this.t_person_my_client2 = new HashSet<t_person_my_client>();
            this.t_person_my_client3 = new HashSet<t_person_my_client>();
            this.t_to = new HashSet<t_to>();
            this.t_to_my_client = new HashSet<t_to_my_client>();
        }
    
        public string Value { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<director_detail> director_detail { get; set; }
        public virtual ICollection<director_detail> director_detail1 { get; set; }
        public virtual ICollection<director_detail> director_detail2 { get; set; }
        public virtual ICollection<director_detail> director_detail3 { get; set; }
        public virtual ICollection<director_detail> director_detail4 { get; set; }
        public virtual ICollection<signatoryDetail> signatoryDetails { get; set; }
        public virtual ICollection<signatoryDetail> signatoryDetails1 { get; set; }
        public virtual ICollection<signatoryDetail> signatoryDetails2 { get; set; }
        public virtual ICollection<signatoryDetail> signatoryDetails3 { get; set; }
        public virtual ICollection<signatoryDetail> signatoryDetails4 { get; set; }
        public virtual ICollection<t_address> t_address { get; set; }
        public virtual ICollection<t_entity> t_entity { get; set; }
        public virtual ICollection<t_from> t_from { get; set; }
        public virtual ICollection<t_from_my_client> t_from_my_client { get; set; }
        public virtual ICollection<t_person_employer> t_person_employer { get; set; }
        public virtual ICollection<t_person_identification> t_person_identification { get; set; }
        public virtual ICollection<t_person_my_client> t_person_my_client { get; set; }
        public virtual ICollection<t_person_my_client> t_person_my_client1 { get; set; }
        public virtual ICollection<t_person_my_client> t_person_my_client2 { get; set; }
        public virtual ICollection<t_person_my_client> t_person_my_client3 { get; set; }
        public virtual ICollection<t_to> t_to { get; set; }
        public virtual ICollection<t_to_my_client> t_to_my_client { get; set; }
    }
}
