//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.goods_services = new HashSet<goods_services>();
            this.reports = new HashSet<report>();
            this.t_account_my_client = new HashSet<t_account_my_client>();
            this.t_foreign_currency = new HashSet<t_foreign_currency>();
            this.t_from_my_client = new HashSet<t_from_my_client>();
        }
    
        public string currency_code_local_id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<goods_services> goods_services { get; set; }
        public virtual ICollection<report> reports { get; set; }
        public virtual ICollection<t_account_my_client> t_account_my_client { get; set; }
        public virtual ICollection<t_foreign_currency> t_foreign_currency { get; set; }
        public virtual ICollection<t_from_my_client> t_from_my_client { get; set; }
    }
}
