//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District_Name
    {
        public District_Name()
        {
            this.t_address = new HashSet<t_address>();
            this.t_person_employer = new HashSet<t_person_employer>();
        }
    
        public string Value { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<t_address> t_address { get; set; }
        public virtual ICollection<t_person_employer> t_person_employer { get; set; }
    }
}
