//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_REPORTED
    {
        public int ID { get; set; }
        public string ErrorFile { get; set; }
        public string FISubjectCode { get; set; }
        public string FISecondarySubjectCode { get; set; }
        public string FIContractCode { get; set; }
        public string ErrorType { get; set; }
        public string ErrorCode { get; set; }
        public string WrongValue { get; set; }
        public string ErrorDescription { get; set; }
        public string AccountingPeriod { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
    }
}
