//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILLER
    {
        public int id { get; set; }
        public string SubjectHeader { get; set; }
        public string SubjectPersonal { get; set; }
        public string SubjectIndividual { get; set; }
        public string SubjectCompany { get; set; }
        public string LinkSubjectOwner { get; set; }
        public string SubjectFooter { get; set; }
        public string ContractHeader { get; set; }
        public string ContractGeneral { get; set; }
        public string ContractInstalment { get; set; }
        public string ContractCard { get; set; }
        public string ContractNonInstlment { get; set; }
        public string ContractSubInfo { get; set; }
        public string LinkContractSubject { get; set; }
        public string ContractFooter { get; set; }
    }
}
