//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funds_type
    {
        public Funds_type()
        {
            this.t_from = new HashSet<t_from>();
            this.t_from_my_client = new HashSet<t_from_my_client>();
            this.t_to = new HashSet<t_to>();
            this.t_to_my_client = new HashSet<t_to_my_client>();
        }
    
        public string value { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<t_from> t_from { get; set; }
        public virtual ICollection<t_from_my_client> t_from_my_client { get; set; }
        public virtual ICollection<t_to> t_to { get; set; }
        public virtual ICollection<t_to_my_client> t_to_my_client { get; set; }
    }
}
