//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_services
    {
        public int goods_services_id { get; set; }
        public string trans_Item_type_id { get; set; }
        public string Item_make { get; set; }
        public string description { get; set; }
        public string previously_registered_to { get; set; }
        public string presently_registered_to { get; set; }
        public Nullable<decimal> estimated_value { get; set; }
        public string status_code_id { get; set; }
        public string status_comments { get; set; }
        public Nullable<decimal> disposed_value { get; set; }
        public string currency_code { get; set; }
        public Nullable<decimal> size { get; set; }
        public string size_uom { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string registration_number { get; set; }
        public string identification_number { get; set; }
        public string Comments { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual t_address t_address { get; set; }
        public virtual Transaction_Item_Status Transaction_Item_Status { get; set; }
        public virtual Transaction_Item_Type Transaction_Item_Type { get; set; }
    }
}
