//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identification_Type
    {
        public Identification_Type()
        {
            this.t_person_identification = new HashSet<t_person_identification>();
        }
    
        public string value { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<t_person_identification> t_person_identification { get; set; }
    }
}
