//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legal_Form_Type
    {
        public Legal_Form_Type()
        {
            this.t_entity = new HashSet<t_entity>();
        }
    
        public string value { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<t_entity> t_entity { get; set; }
    }
}
