//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_SUBJECT_CONTRACT
    {
        public int id { get; set; }
        public string recType { get; set; }
        public string fiCode { get; set; }
        public string branch { get; set; }
        public string linkType { get; set; }
        public string fiSubjectCodeBorrower { get; set; }
        public string fiSubjectCodeLinked { get; set; }
        public string fiContCode { get; set; }
        public string filler { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string accountingPeriod { get; set; }
    }
}
