//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWNER_INFO
    {
        public int id { get; set; }
        public string owenerId { get; set; }
        public string ownedComapy { get; set; }
        public string role { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
    }
}
