//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int rentity_id { get; set; }
        public string rentity_branch { get; set; }
        public string submission_code_id { get; set; }
        public string report_code_id { get; set; }
        public string entity_reference { get; set; }
        public string fiu_ref_number { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public string currency_code_local_id { get; set; }
        public Nullable<int> reporting_person_id { get; set; }
        public Nullable<int> Location_id { get; set; }
        public string reason { get; set; }
        public string action { get; set; }
        public string transaction_id { get; set; }
        public string Activity_id { get; set; }
        public string report_indicators { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Report_Code Report_Code { get; set; }
        public virtual Submission_type Submission_type { get; set; }
        public virtual t_address t_address { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
        public virtual t_transaction t_transaction { get; set; }
    }
}
