//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_type
    {
        public Role_type()
        {
            this.director_detail = new HashSet<director_detail>();
            this.signatoryDetails = new HashSet<signatoryDetail>();
        }
    
        public int id { get; set; }
        public string value { get; set; }
        public string description { get; set; }
        public string entityCode { get; set; }
    
        public virtual ICollection<director_detail> director_detail { get; set; }
        public virtual ICollection<signatoryDetail> signatoryDetails { get; set; }
    }
}
