//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signatoryDetail
    {
        public signatoryDetail()
        {
            this.t_address = new HashSet<t_address>();
            this.t_person_identification = new HashSet<t_person_identification>();
            this.t_phone = new HashSet<t_phone>();
        }
    
        public int sign_id { get; set; }
        public string gender { get; set; }
        public string Title { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string prefix { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string Birth_place { get; set; }
        public string mothers_name { get; set; }
        public string alias { get; set; }
        public string SSN { get; set; }
        public string passport_number { get; set; }
        public string passport_country { get; set; }
        public string id_number { get; set; }
        public string Nationality1 { get; set; }
        public string Nationality2 { get; set; }
        public string Nationality3 { get; set; }
        public string residence { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public string deceased { get; set; }
        public Nullable<System.DateTime> deceased_date { get; set; }
        public string tax_number { get; set; }
        public string tax_reg_number { get; set; }
        public string source_of_wealth { get; set; }
        public string comments { get; set; }
        public Nullable<int> role_id { get; set; }
        public string isprimary { get; set; }
        public Nullable<int> t_account_my_client_id { get; set; }
    
        public virtual Country_Codes Country_Codes { get; set; }
        public virtual Country_Codes Country_Codes1 { get; set; }
        public virtual Country_Codes Country_Codes2 { get; set; }
        public virtual Country_Codes Country_Codes3 { get; set; }
        public virtual Country_Codes Country_Codes4 { get; set; }
        public virtual Role_type Role_type { get; set; }
        public virtual t_account_my_client t_account_my_client { get; set; }
        public virtual ICollection<t_address> t_address { get; set; }
        public virtual ICollection<t_person_identification> t_person_identification { get; set; }
        public virtual ICollection<t_phone> t_phone { get; set; }
    }
}
