//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignatoryInfo
    {
        public int sign_Id { get; set; }
        public string accountNumber { get; set; }
        public Nullable<int> signatorId { get; set; }
        public string isprimary { get; set; }
        public Nullable<int> director_id { get; set; }
    
        public virtual director_detail director_detail { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
    }
}
