//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT_INFORMATION
    {
        public string accountingPeriod { get; set; }
        public string recType { get; set; }
        public string fiCode { get; set; }
        public string branch { get; set; }
        public string fiSubCode { get; set; }
        public string title { get; set; }
        public string subName { get; set; }
        public string tradeName { get; set; }
        public string sectorType { get; set; }
        public string sectorCode { get; set; }
        public string TIN { get; set; }
        public string parAdd { get; set; }
        public string parPost { get; set; }
        public string parDist { get; set; }
        public string parCountry { get; set; }
        public string presentAdd { get; set; }
        public string presentPost { get; set; }
        public string presentDist { get; set; }
        public string presentCountry { get; set; }
        public string phone { get; set; }
        public string legalForm { get; set; }
        public string owTitle { get; set; }
        public string owName { get; set; }
        public string fatherTitle { get; set; }
        public string fatherName { get; set; }
        public string motherTitle { get; set; }
        public string mothrName { get; set; }
        public string husTitle { get; set; }
        public string husName { get; set; }
        public string gender { get; set; }
        public string owBirthDate { get; set; }
        public string owBirthPlace { get; set; }
        public string owBirthCountry { get; set; }
        public string isNIDAvailable { get; set; }
        public string owTIN { get; set; }
        public string FactoryAdd { get; set; }
        public string FactoryPost { get; set; }
        public string FactoryDist { get; set; }
        public string FactoryCountry { get; set; }
        public string owDocType { get; set; }
        public string owDocNo { get; set; }
        public string owDocIssueDate { get; set; }
        public string owDocIssueCountry { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string isImportedFromDBF { get; set; }
        public string isBorrower { get; set; }
        public string isOwner { get; set; }
        public string isGuarantor { get; set; }
        public string isCoBorrower { get; set; }
        public string isRejected { get; set; }
        public string NID { get; set; }
        public string businessAdd { get; set; }
        public string businessPost { get; set; }
        public string businessDist { get; set; }
        public string businessCountry { get; set; }
        public string rjscNumber { get; set; }
        public string rjscDate { get; set; }
        public string crgScore { get; set; }
        public string creditRating { get; set; }
    }
}
