//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission_type
    {
        public Submission_type()
        {
            this.reports = new HashSet<report>();
        }
    
        public string submission_code_id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<report> reports { get; set; }
    }
}
