//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_my_client
    {
        public t_account_my_client()
        {
            this.signatoryDetails = new HashSet<signatoryDetail>();
            this.t_from_my_client = new HashSet<t_from_my_client>();
            this.t_from = new HashSet<t_from>();
            this.t_to_my_client = new HashSet<t_to_my_client>();
            this.t_to = new HashSet<t_to>();
        }
    
        public int t_account_my_client_id { get; set; }
        public string Instituation_name { get; set; }
        public string institution_code { get; set; }
        public string swift { get; set; }
        public string Non_banking_institution { get; set; }
        public string Branch { get; set; }
        public string Account { get; set; }
        public string currency_code_id { get; set; }
        public string account_name { get; set; }
        public string iban { get; set; }
        public string client_number { get; set; }
        public string personal_account_type_id { get; set; }
        public Nullable<int> t_entity_id { get; set; }
        public Nullable<System.DateTime> opened { get; set; }
        public Nullable<System.DateTime> closed { get; set; }
        public string status_code_id { get; set; }
        public string beneficiary { get; set; }
        public string beneficiary_comment { get; set; }
        public string comments { get; set; }
        public string entityCode { get; set; }
        public Nullable<int> t_person_Id { get; set; }
        public Nullable<int> branchId { get; set; }
        public byte[] signCard { get; set; }
        public string person_role { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Account_Person_Role Account_Person_Role { get; set; }
        public virtual Account_Status_Type Account_Status_Type { get; set; }
        public virtual Account_Type Account_Type { get; set; }
        public virtual Branch_Info Branch_Info { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<signatoryDetail> signatoryDetails { get; set; }
        public virtual t_entity t_entity { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
        public virtual t_person_my_client t_person_my_client1 { get; set; }
        public virtual ICollection<t_from_my_client> t_from_my_client { get; set; }
        public virtual ICollection<t_from> t_from { get; set; }
        public virtual ICollection<t_to_my_client> t_to_my_client { get; set; }
        public virtual ICollection<t_to> t_to { get; set; }
    }
}
