//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_entity
    {
        public t_entity()
        {
            this.director_detail = new HashSet<director_detail>();
            this.t_account_my_client = new HashSet<t_account_my_client>();
            this.t_address = new HashSet<t_address>();
            this.t_from_my_client = new HashSet<t_from_my_client>();
            this.t_from = new HashSet<t_from>();
            this.t_person_identification = new HashSet<t_person_identification>();
            this.t_phone = new HashSet<t_phone>();
            this.t_to_my_client = new HashSet<t_to_my_client>();
            this.t_to = new HashSet<t_to>();
        }
    
        public int t_entity_id { get; set; }
        public string Name { get; set; }
        public string Commercial_name { get; set; }
        public string Incorporation_legal_form_id { get; set; }
        public string incorporation_number { get; set; }
        public string Business { get; set; }
        public string Email { get; set; }
        public string url { get; set; }
        public string incorporation_state { get; set; }
        public string incorporation_country_code { get; set; }
        public string incorporation_date { get; set; }
        public string business_closed { get; set; }
        public string date_business_closed { get; set; }
        public string tax_numebr { get; set; }
        public string tax_registeration_number { get; set; }
        public string comments { get; set; }
        public Nullable<int> branchId { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Branch_Info Branch_Info { get; set; }
        public virtual Country_Codes Country_Codes { get; set; }
        public virtual ICollection<director_detail> director_detail { get; set; }
        public virtual Legal_Form_Type Legal_Form_Type { get; set; }
        public virtual ICollection<t_account_my_client> t_account_my_client { get; set; }
        public virtual ICollection<t_address> t_address { get; set; }
        public virtual ICollection<t_from_my_client> t_from_my_client { get; set; }
        public virtual ICollection<t_from> t_from { get; set; }
        public virtual ICollection<t_person_identification> t_person_identification { get; set; }
        public virtual ICollection<t_phone> t_phone { get; set; }
        public virtual ICollection<t_to_my_client> t_to_my_client { get; set; }
        public virtual ICollection<t_to> t_to { get; set; }
    }
}
