//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_from_my_client
    {
        public int t_from_my_client_id { get; set; }
        public string from_funds_code_id { get; set; }
        public string from_funds_comment { get; set; }
        public string from_foreign_currency_id { get; set; }
        public Nullable<int> t_conductor_id { get; set; }
        public Nullable<int> from_account_id { get; set; }
        public Nullable<int> from_person_id { get; set; }
        public Nullable<int> from_entity_id { get; set; }
        public string from_country_id { get; set; }
    
        public virtual Country_Codes Country_Codes { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Funds_type Funds_type { get; set; }
        public virtual t_account_my_client t_account_my_client { get; set; }
        public virtual t_entity t_entity { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
        public virtual t_person_my_client t_person_my_client1 { get; set; }
    }
}
