//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_person_identification
    {
        public int t_person_identification_id { get; set; }
        public string type_id { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string issued_by { get; set; }
        public string issue_country_id { get; set; }
        public string comments { get; set; }
        public Nullable<int> t_person_my_client_id { get; set; }
        public Nullable<int> directors_id { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<int> signatory_id { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Country_Codes Country_Codes { get; set; }
        public virtual director_detail director_detail { get; set; }
        public virtual Identification_Type Identification_Type { get; set; }
        public virtual signatoryDetail signatoryDetail { get; set; }
        public virtual t_entity t_entity { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
    }
}
