//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_person_employer
    {
        public t_person_employer()
        {
            this.t_person_my_client1 = new HashSet<t_person_my_client>();
        }
    
        public int EmployerId { get; set; }
        public string name { get; set; }
        public Nullable<int> addressTypeId { get; set; }
        public string address { get; set; }
        public string townid { get; set; }
        public string cityid { get; set; }
        public string stateid { get; set; }
        public string zip { get; set; }
        public string country_code_id { get; set; }
        public Nullable<int> contactTypeId { get; set; }
        public string communcationTypeId { get; set; }
        public string country_prefix { get; set; }
        public string phonenumber { get; set; }
        public string extension { get; set; }
        public Nullable<int> t_person_my_client_id { get; set; }
    
        public virtual Communication_Type Communication_Type { get; set; }
        public virtual Contact_Type Contact_Type { get; set; }
        public virtual Contact_Type Contact_Type1 { get; set; }
        public virtual Country_Codes Country_Codes { get; set; }
        public virtual District_Name District_Name { get; set; }
        public virtual Division_Name Division_Name { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
        public virtual ICollection<t_person_my_client> t_person_my_client1 { get; set; }
    }
}
