//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_person_my_client
    {
        public t_person_my_client()
        {
            this.reports = new HashSet<report>();
            this.SignatoryInfoes = new HashSet<SignatoryInfo>();
            this.t_account_my_client = new HashSet<t_account_my_client>();
            this.t_account_my_client1 = new HashSet<t_account_my_client>();
            this.t_address = new HashSet<t_address>();
            this.t_from = new HashSet<t_from>();
            this.t_from1 = new HashSet<t_from>();
            this.t_from_my_client = new HashSet<t_from_my_client>();
            this.t_from_my_client1 = new HashSet<t_from_my_client>();
            this.t_person_employer = new HashSet<t_person_employer>();
            this.t_person_identification = new HashSet<t_person_identification>();
            this.t_phone = new HashSet<t_phone>();
            this.t_to_my_client = new HashSet<t_to_my_client>();
            this.t_to = new HashSet<t_to>();
        }
    
        public int t_person_my_client_id { get; set; }
        public string gender { get; set; }
        public string Title { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string prefix { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string Birth_place { get; set; }
        public string mothers_name { get; set; }
        public string fathers_Name { get; set; }
        public string SSN { get; set; }
        public string passport_number { get; set; }
        public string passport_country { get; set; }
        public string id_number { get; set; }
        public string Nationality1_id { get; set; }
        public string Nationality2_id { get; set; }
        public string Nationality3_id { get; set; }
        public string residence { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> employer_id { get; set; }
        public string deceased { get; set; }
        public Nullable<System.DateTime> deceased_date { get; set; }
        public string tax_number { get; set; }
        public string tax_reg_numebr { get; set; }
        public string source_of_wealth { get; set; }
        public string comments { get; set; }
        public Nullable<int> branchId { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Branch_Info Branch_Info { get; set; }
        public virtual Country_Codes Country_Codes { get; set; }
        public virtual Country_Codes Country_Codes1 { get; set; }
        public virtual Country_Codes Country_Codes2 { get; set; }
        public virtual Country_Codes Country_Codes3 { get; set; }
        public virtual ICollection<report> reports { get; set; }
        public virtual ICollection<SignatoryInfo> SignatoryInfoes { get; set; }
        public virtual ICollection<t_account_my_client> t_account_my_client { get; set; }
        public virtual ICollection<t_account_my_client> t_account_my_client1 { get; set; }
        public virtual ICollection<t_address> t_address { get; set; }
        public virtual ICollection<t_from> t_from { get; set; }
        public virtual ICollection<t_from> t_from1 { get; set; }
        public virtual ICollection<t_from_my_client> t_from_my_client { get; set; }
        public virtual ICollection<t_from_my_client> t_from_my_client1 { get; set; }
        public virtual ICollection<t_person_employer> t_person_employer { get; set; }
        public virtual t_person_employer t_person_employer1 { get; set; }
        public virtual ICollection<t_person_identification> t_person_identification { get; set; }
        public virtual ICollection<t_phone> t_phone { get; set; }
        public virtual ICollection<t_to_my_client> t_to_my_client { get; set; }
        public virtual ICollection<t_to> t_to { get; set; }
    }
}
