//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_phone
    {
        public int t_phone_id { get; set; }
        public int tph_contact_type_id { get; set; }
        public string tph_communication_type_id { get; set; }
        public string tph_country_prefix { get; set; }
        public string tph_number { get; set; }
        public string tph_extension { get; set; }
        public string comments { get; set; }
        public Nullable<int> t_person_my_client_id { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<int> director_id { get; set; }
        public Nullable<int> signatory_id { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Communication_Type Communication_Type { get; set; }
        public virtual Contact_Type Contact_Type { get; set; }
        public virtual director_detail director_detail { get; set; }
        public virtual signatoryDetail signatoryDetail { get; set; }
        public virtual t_entity t_entity { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
    }
}
