//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_to
    {
        public int t_to_id { get; set; }
        public string to_funds_code_id { get; set; }
        public string to_funds_comment { get; set; }
        public Nullable<int> to_foreign_currency_id { get; set; }
        public Nullable<int> to_account_id { get; set; }
        public Nullable<int> to_person_id { get; set; }
        public Nullable<int> to_entity_id { get; set; }
        public string to_country_id { get; set; }
    
        public virtual Country_Codes Country_Codes { get; set; }
        public virtual Funds_type Funds_type { get; set; }
        public virtual t_account_my_client t_account_my_client { get; set; }
        public virtual t_entity t_entity { get; set; }
        public virtual t_foreign_currency t_foreign_currency { get; set; }
        public virtual t_person_my_client t_person_my_client { get; set; }
    }
}
