//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_transaction
    {
        public t_transaction()
        {
            this.reports = new HashSet<report>();
        }
    
        public string transactionnumber { get; set; }
        public string Internal_ref_number { get; set; }
        public string transaction_location { get; set; }
        public string transaction_description { get; set; }
        public System.DateTime date_transaction { get; set; }
        public string teller { get; set; }
        public string authorized { get; set; }
        public string late_deposit { get; set; }
        public Nullable<System.DateTime> date_posting { get; set; }
        public Nullable<System.DateTime> value_date { get; set; }
        public string transmode_code { get; set; }
        public string transmode_comment { get; set; }
        public Nullable<decimal> amount_local { get; set; }
        public Nullable<int> goods_services_id { get; set; }
        public string comments { get; set; }
        public string accnoutno { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string cifno { get; set; }
    
        public virtual ICollection<report> reports { get; set; }
        public virtual Transaction_Mode Transaction_Mode { get; set; }
    }
}
