//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempTransaction
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string accno { get; set; }
        public string voucherno { get; set; }
        public string in_out { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> cif { get; set; }
        public string cifname { get; set; }
    }
}
