//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Item_Status
    {
        public Transaction_Item_Status()
        {
            this.goods_services = new HashSet<goods_services>();
        }
    
        public string value { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<goods_services> goods_services { get; set; }
    }
}
