//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOAML.DomainModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInfo
    {
        public int id { get; set; }
        public string userNme { get; set; }
        public string userpassword { get; set; }
        public Nullable<int> branchId { get; set; }
        public Nullable<int> category { get; set; }
    
        public virtual Branch_Info Branch_Info { get; set; }
    }
}
